### ISSUE TITLE
Can't Build after update to v0.4.4

### ISSUE THREAD

**Issue by MHarmony** [okgrow/graphql-scalars#32]
After updating to v0.4.4 my angular project fails to build successfully. I am running node version 11.9.0, angular cli version 7.3.1, and typescript 3.2.4. My project builds fine if I rollback to v0.4.3.

The following errors are displayed:

```
ERROR in node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(4,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(4,17): error TS2451: Cannot redeclare block-scoped variable 'EmailAddress'.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(5,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(6,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(7,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(8,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(9,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(10,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(11,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(12,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(13,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(14,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(14,17): error TS2451: Cannot redeclare block-scoped variable 'EmailAddress'.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(15,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(16,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(17,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] node_modules/@okgrow/graphql-scalars/graphql-scalars.d.ts(19,3): error TS1038: A 'declare' modifier cannot be used in an already ambient context.

[1] src/app/shared/interfaces/employee.interface.ts(16,20): error TS2304: Cannot find name 'EmailAddress'.

[1] src/app/shared/interfaces/employee.interface.ts(17,24): error TS2304: Cannot find name 'PhoneNumber'.

[1] src/app/shared/interfaces/employee.interface.ts(18,24): error TS2304: Cannot find name 'PhoneNumber'.
```

**Comment by ccuilla** [comment]
This should be fixed on v0.4.5.
